import type { AddStudentFormValues } from './types'

export const getTestStudentFormValues = (): AddStudentFormValues => {
  const currentAddress = {
    streetUnit: '12',
    street: 'Rizal Street',
    subdivision: 'Green Valley Subdivision',
    barangay: 'Balzain',
    city: 'Tuguegarao City',
    province: 'Cagayan',
    zipCode: '3500',
  }

  return {
    admitType: 'new',
    schoolYear: '2025-2026',
    term: '1',
    studentType: 'regular',
    grade: '11',
    seniorHighProgram: 'stem',
    learnersReferenceNumber: '123456789012',
    firstName: 'Juan',
    middleName: 'Dela',
    lastName: 'Cruz',
    suffix: 'Jr.',
    gender: 'male',
    status: 'single',
    citizenship: 'Filipino',
    dateOfBirth: '2008-05-15',
    birthplace: 'Tuguegarao City, Cagayan',
    religion: 'Roman Catholic',
    currentAddress,
    permanentAddress: { ...currentAddress },
    sameAsCurrentAddress: true,
    telephone: '078-123-4567',
    mobile: '09171234567',
    email: 'juan.delacruz.test@student.edu',
    schoolAttended: {
      schoolType: 'public',
      schoolName: 'Cagayan National High School',
      program: 'STEM',
      dateOfGraduation: '2024-03-20',
      schoolYear: '2024-2025',
      yearLevel: '11',
      term: '2',
    },
    father: {
      firstName: 'Pedro',
      lastName: 'Cruz',
      middleInitial: 'S',
      suffix: '',
      mobile: '09181112233',
      email: 'pedro.cruz.test@email.com',
      occupation: 'Engineer',
      relationship: '',
    },
    mother: {
      firstName: 'Maria',
      lastName: 'Cruz',
      middleInitial: 'L',
      suffix: '',
      mobile: '09192223344',
      email: 'maria.cruz.test@email.com',
      occupation: 'Teacher',
      relationship: '',
    },
    guardian: {
      firstName: 'Ana',
      lastName: 'Santos',
      middleInitial: 'M',
      suffix: '',
      mobile: '09193334455',
      email: 'ana.santos.test@email.com',
      occupation: 'Business Owner',
      relationship: 'Aunt',
    },
    documents: {
      juniorSenior: {
        form138: true,
        form137: true,
        birthCertificate: true,
        goodMoral: false,
      },
      transferee: {
        transferCertificate: false,
        form138Shs: true,
        form137Shs: false,
        birthCertificate: true,
        goodMoral: true,
      },
      uploadedFiles: [
        { id: 'test-1', name: 'form-138.pdf', size: 245760 },
        { id: 'test-2', name: 'birth-certificate.png', size: 1048576 },
      ],
    },
  }
}
